FORMAT: 1A
HOST: http://api.factory.zone/api/v1/

# Project API 
Provides services for Project features 

# Group Projects 
Access to Project Resources

All requests must be authenticated 

## Projects [/projects{?search_param,page,size}]

### Create Project [POST]
Create a Project owned by the currently authenticated user.

The API endpoint may refuse to complete the request if the authenticated user has exceeded the total number of allowed projects for his or her account.

+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "user_id": 2
                "company_id" : 1
                "department_id" : 2
                "projectName" : "Loon"
                "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "projectDescription" : "Make Internet Baloons"
                "projectDeadline" : "2018-01-31 00:00:01"
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /projects/:id
    
    + Body
    
            {
                "user_id":2
                "company_id":1
                "department_id": 2
                "project_id": 1
                "projectName" : "Loon"
                "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "projectDescription" : "Make Internet Baloons"
                "createdAt" : "2017-6-21 08:12:05"
                "projectStatus" : 1
                "projectDeadline" : "2018-01-31 00:00:01"
                "is_archived": false
            }

### List Projects [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body        
        
            {
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "projects":
                [
                    {
                        "user_id":5
                        "company_id":3
                        "department_id": 2
                        "project_id": 1
                        "projectName" : "Ara"
                        "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "projectDescription" : "Create modular phones"
                        "createdAt" : "2017-6-21 08:12:05"
                        "projectStatus": 1
                        "projectDeadline" : "2017-12-01 13:21:14"
                        "is_archived": false
                    },
                    {
                        "user_id":2
                        "company_id":1
                        "department_id": 3
                        "project_id": 1
                        "projectName" : "Tango"
                        "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "projectDescription" : "Make augumented reality real"
                        "createdAt" : "2016-09-12 02:2:45"
                        "projectStatus": 3
                        "projectDeadline" : "2018-1-01 12:00:00"
                        "is_archived": false
                    },
                    {
                        "user_id":3
                        "company_id":1
                        "department_id": 3
                        "project_id": 1
                        "projectName" : "Waymo"
                        "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "projectDescription" : "Create self-driving cars"
                        "createdAt" : "2016-09-12 02:2:45"
                        "projectStatus" : 2
                        "projectDeadline" : "2018-1-01 12:00:00"
                        "is_archived": true
                    } 
                ]
            }

## Project [/projects/{project_id}]

+ Parameters
    + project_id(required, number,`1`)

### View Project [GET]

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
            
            {
                "user_id" : 3  
                "company_id" : 1
                "department_id" : 2
                "projectName" : "Ara"
                "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "projectDescription" : "Create modular phones"
                "createdAt" : "2017-6-21 08:12:05"
                "projectStatus" :3
                "projectDeadline" : "2017-12-01 13:21:14"
                "is_archived": false
            }

### Edit Project [PUT]
+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "projectName" : "Loon"
                "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "projectDescription" : "Make Baloons That Grant Internet Access"
                "projectStatus" : 3
                "projectDeadline" : "2018-01-31 00:00:01"
                "is_archived": true
            }    
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /projects/:id
    
    + Body
    
            {
                "company_id":1
                "department_id":2
                "user_id":4
                "projectName" : "Loon"
                "projectImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "projectDescription" : "Make Baloons That Grant Internet Access"
                "createdAt" : "2017-6-21 08:12:05"
                "projectStatus" : 3
                "projectDeadline" : "2018-01-31 00:00:01"
                "is_archived": true
                "updatedAt": "2017-6-21 11:10:35"
            }
       
### Delete Project [DELETE]

+ Response 204

# Group Task 
Access to Project Task Resources

## Tasks [/projects/{project_id}/tasks/{?page,size}]

+ Parameters
    + project_id(required, number,`1`)

### Add a Task [POST]
Create a Task Assigned to a  Project owned by the currently authenticated user.

The API endpoint may refuse to complete the request if the authenticated user has exceeded the total number of allowed tasks for his or her account.

+   Request (application/json)
            +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "project_id" : "1"
                "taskName" : "Research"
                "taskDescription" : "Make findings into the proposed project"
                "taskDeadline" : "2018-01-31 00:00:01"
            }    
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /projects/:id/task/:id
    
    + Body
    
            {
                "company_id":1
                "department_id":2
                "user_id":3
                "project_id":2
                "task_id":1
                "taskName" : "Research"
                "taskDescription" : "Make findings into the proposed project"
                "tasktDeadline" : "2018-01-31 00:00:01"
                "createdAt" : "2017-6-21 08:12:05"
                "taskStatus" : 1
                "taskDeadline" : "2018-01-31 00:00:01"
            }

### List Tasks [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
            
            {
                "tasks":
                [
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Research"
                        "taskDescription" : "Carry out research for project"
                        "createdAt" : "2017-6-21 08:12:05"
                        "taskStatus" :3
                        "taskDeadline" : "2017-12-01 13:21:14"
                    },
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Develop Wireframe"
                        "taskDescription" : "Design Wireframe for project"
                        "createdAt" : "2017-6-21 08:30:15"
                        "taskStatus" :1
                        "taskDeadline" : "2017-12-07 08:30:14"
                    },
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Design Mock-up"
                        "taskDescription" : "Design Mock-up for project"
                        "createdAt" : "2017-6-21 08:40:05"
                        "taskStatus" :2
                        "taskDeadline" : "2018-01-01 00:00:00"
                    },                    
            }

## Task [/project/{project_id}/tasks/{task_id}]

+ Parameters
    + project_id   (required, number, `4`)
    + task_id   (required, number, `1`)

### View Task [GET]

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
            
            {
                "company_id":1
                "department_id":2
                "user_id":3
                "project_id":2
                "company_id": 1
                "department_id": 2
                "project_id":1
                "taskName" : "Research"
                "taskDescription" : "Carry out research for project"
                "createdAt" : "2017-6-21 08:12:05"
                "taskStatus" :3
                "taskDeadline" : "2017-12-01 13:21:14"
            }

### Edit Task [PUT]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "taskName" : "Research"
                "taskDescription" : "Make findings into the proposed project"
                "taskDeadline" : "2018-01-31 00:00:01"
            }    
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /projects/:id/task:id
    
    + Body
    
            {
                "company_id": 1
                "department_id": 2
                "user_id":2
                "project_id":1
                "taskName" : "Draw Wireframe"
                "taskDescription" : "Make Wireframe of the project"
                "taskDeadline" : "2018-01-31 00:00:01"
                "updatedAT": "2018-02-31 03:20:00"
            }

### Delete Task [DELETE]

+ Response 204

# Group Team 
Access to Project Team Resources

## Teams [/teams{?page,size}]

### Create Team [POST]

+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "TeamName" : "Artisan"
                "TeamInfo" : "Artisan is a team of back-end craftsmen"
                "project_id": 1
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /teams/:id
    
    + Body
    
            {
                "company_id": 1
                "department_id": 2
                "user_id":1
                "team_id":2
                "TeamName" : "Artisan"
                "TeamInfo" : "Artisan is a team of back-end craftsmen"
                "createdAt" : "2017-6-21 08:12:05"
            }

### List Teams [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
            
            {
                "tasks":
                [
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Research"
                        "taskDescription" : "Carry out research for project"
                        "createdAt" : "2017-6-21 08:12:05"
                        "taskStatus" :3
                        "taskDeadline" : "2017-12-01 13:21:14"
                    },
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Develop Wireframe"
                        "taskDescription" : "Design Wireframe for project"
                        "createdAt" : "2017-6-21 08:30:15"
                        "taskStatus" :1
                        "taskDeadline" : "2017-12-07 08:30:14"
                    },
                    {
                        "company_id":1
                        "department_id":2
                        "user_id":3
                        "project_id":2
                        "taskName" : "Design Mock-up"
                        "taskDescription" : "Design Mock-up for project"
                        "createdAt" : "2017-6-21 08:40:05"
                        "taskStatus" :2
                        "taskDeadline" : "2018-01-01 00:00:00"
                    },                    
            }
            
## Team [/teams/{team_id}]

### Edit Team [PUT]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "TeamName" : "Artisan"
                "TeamInfo" : "Artisan is a team of back-end ninjas"
                "project_id": 1
            }     
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /teams:id
    
    + Body
    
            {
                "company_id": 1
                "department_id": 2
                "user_id":1
                "team_id":2                
                "TeamName" : "Artisan"
                "TeamInfo" : "Artisan is a team of back-end ninjas"
                "updatedAT": "2018-02-31 03:20:00"
            }

### View Team [GET]

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "company_id": 1
                "department_id": 2
                "user_id":3
                "team_id":2
                "teamName": "DreamTeam"
                "teamInfo": "Best team in the land"
                "createdAt":"2017-12-01 13:21:14"
                "updatedAt": "2017-12-01 21:00:00"
            }

### Delete Team [DELETE]

+ Response 204

# Group Department

## Departments [/company/{company_id}/departments{?page,size}]

### Create Department [POST]

+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "departmentName" : "Sales"
                "departmentInfo" : "They close the deal, doesn't seem like too much work"
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /departments/:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "department_id":1
                "departmentName" : "Sales"
                "departmentInfo" : "They close the deal, doesn't seem like too much work"
                "createdAt" : "2017-6-21 08:12:05"
            }

### List Departments[GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)

    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600
    + Body
        
            {
                                    
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "departments":
                [
                    {
                        "user_id":1
                        "company_id":1
                        "department_id":1
                        "departmentName" : "Design"
                        "departmentInfo" : "They make everything look great and they really shouldn't be with marketing"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    },
                    {
                        "user_id":1
                        "company_id":1
                        "department_id":2
                        "departmentName" : "Marketing"
                        "departmentInfo" : "They sell your product, they can sell you a pile of poop"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    },
                    {
                        "user_id":2
                        "company_id":1
                        "department_id":3
                        "departmentName" : "Sales"
                        "departmentInfo" : "They close the deal, doesn't seem like too much work"
                        "createdAt" : "2017-6-21 08:12:05"
                        "updatedAt" : "2017-12-01 13:21:14"
                    }
                ]
            }

## Department [/company/{company_id}/departments/{department_id}]

### Edit Department [PUT]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look shiny and they really shouldn't be with marketing"
            }     
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /departments:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "department_id":1
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look shiny and they really shouldn't be with marketing"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAT": "2018-02-31 03:20:00"
            }

### View Department [GET]
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "user_id":2
                "company_id":1
                "department_id":1
                "departmentName" : "Design"
                "departmentInfo" : "They make everything look great and they really shouldn't be with marketing"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAt" : "2017-12-01 13:21:14"
            }

### Delete Department [DELETE]

+ Response 204

# Group Company

## Company [/company{?page,size}]

### Create Company[POST]


+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /company/:id
    
    + Body
    
            {
                "user_id":2
                "company_id":1
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "createdAt":"2017-6-21 08:12:05"

            }
###

### List Companies [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
            
            {
                                    
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "companies":
                [
                    {
                        "user_id":2
                        "company_id": 1
                        "companyName" : "Gaagle"
                        "companyDescription" : "We build everything"
                        "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "companyURL" : "gaagle.factory.zone"
                        "createdAt":"2017-12-01 13:21:14"
                        "updatedAt": "2017-12-01 21:00:00"
                    },
                    {
                        "user_id":2
                        "company_id": 3
                        "companyName" : "Amzin"
                        "companyDescription" : "We sell everything"
                        "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "companyURL" : "amzin.factory.zone"
                        "createdAt":"2017-12-01 13:21:14"
                        "updatedAt": "2017-12-01 21:00:00"
                    }
                ]
            }

### Edit Company [PUT]
+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build life"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
            }     
        
            
            
+ Response 200 (application/json)

    + Headers 
        
            Location: /departments:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "companyName" : "Gaagle"
                "companyDescription" : "We build life"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAT": "2018-02-31 03:20:00"
            }

## Companies [/company/{company_id}]

### View Comapany [GET]
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "user_id":2
                "company_id":1
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAt" : "2017-12-01 13:21:14"
            }
            
### Delete Department [DELETE]

+ Response 204

# Group User 

# Group Notice Board